// This file should be generated by 'npm run build' in the functions directory.
// Its content will be created from the compiled TypeScript source.
// This placeholder ensures the file exists but its content is irrelevant until build.
"use strict";
