'use client';

import { useState, useEffect, useRef } from 'react';
import Image from 'next/image';
import { Loader2, Sparkles, X, Move, ZoomIn, ZoomOut } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { httpsCallable } from 'firebase/functions';
import { functions } from '@/lib/firebase';
import type { CreatorDesign, ApparelType } from '@/types/creator-lab';
import { DESIGN_OPTIONS, type BadgeShape } from '@/types/apparel-design';
import { STYLE_TEMPLATES, type StyleTemplate } from '@/types/promptTemplate';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import Draggable from 'react-draggable';

interface DesignStudioModalProps {
  apparelType: ApparelType;
  surface?: 'front' | 'back';
  onComplete: (design: CreatorDesign) => void;
  onCancel: () => void;
}

export function DesignStudioModal({ apparelType, surface, onComplete, onCancel }: DesignStudioModalProps) {
  const { currentUser } = useAuth();
  const { toast } = useToast();
  const [subject, setSubject] = useState('');
  const [selectedDesignOption, setSelectedDesignOption] = useState<string>('0'); // Index of selected option
  const [selectedTemplateId, setSelectedTemplateId] = useState<number | null>(null);
  const [editablePrompt, setEditablePrompt] = useState(''); // User can edit final prompt
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedDesign, setGeneratedDesign] = useState<CreatorDesign | null>(null);
  const [isPositioning, setIsPositioning] = useState(false); // NEW: Show positioning UI
  const [isFinalizing, setIsFinalizing] = useState(false); // NEW: Creating final composite
  const [logoPosition, setLogoPosition] = useState({ x: 0, y: 0 }); // NEW: Logo drag position
  const [logoScale, setLogoScale] = useState(0.5); // NEW: Logo size (50% default)
  const apparelContainerRef = useRef<HTMLDivElement>(null); // NEW: For positioning calculations

  // Get style templates for current apparel type
  const styleTemplates = STYLE_TEMPLATES.filter(t => t.apparelType === apparelType);
  
  // Set default template when component mounts or apparel changes
  useEffect(() => {
    if (styleTemplates.length > 0 && !selectedTemplateId) {
      setSelectedTemplateId(styleTemplates[0].id);
    }
  }, [apparelType, styleTemplates, selectedTemplateId]);

  const selectedTemplate = styleTemplates.find(t => t.id === selectedTemplateId) || styleTemplates[0];

  // Build auto-generated prompt by replacing placeholder
  const autoGeneratedPrompt = selectedTemplate 
    ? selectedTemplate.prompt.replace('[USER SUBJECT HERE]', subject.trim() || 'your design')
    : '';

  // Update editable prompt when auto-generated changes
  useEffect(() => {
    if (autoGeneratedPrompt) {
      setEditablePrompt(autoGeneratedPrompt);
    }
  }, [autoGeneratedPrompt]);

  // Get design options for current apparel type
  const designOptions = DESIGN_OPTIONS[apparelType] || [];
  const selectedOption = designOptions[parseInt(selectedDesignOption)] || designOptions[0];

  // Get dynamic placeholder based on apparel type
  const getPlaceholder = () => {
    if (apparelType === 'Cap' || apparelType === 'Beanie') {
      return "Example: A minimalist mountain peak logo with sunset colors...";
    }
    return "Example: A vibrant phoenix rising from flames, bold geometric style...";
  };

  const userCredits = currentUser?.credits || 0;

  // Get apparel preview image
  const getApparelImage = () => {
    const surfaceSuffix = surface ? `-${surface}` : '-front';
    const imageMap: Record<string, string> = {
      'Cap': '/images/apparel/black-cap.jpg',
      'Beanie': '/images/apparel/black-beannie.jpg',
      'T-Shirt': `/images/apparel/black-tshirt${surfaceSuffix}.jpg`,
      'Long T-Shirt': `/images/apparel/black-long-sleeve-sweatshirt${surfaceSuffix}.jpg`,
      'Hoodie': `/images/apparel/black-hoodie${surfaceSuffix}.jpg`,
      'Backpack': '/images/apparel/black-backpack.jpg',
    };
    return imageMap[apparelType] || '/images/apparel/black-tshirt-front.jpg';
  };

  const handleGenerate = async () => {
    if (!subject.trim()) {
      toast({
        title: 'Subject Required',
        description: 'Please describe what you want on your design.',
        variant: 'destructive',
      });
      return;
    }

    if (userCredits < 10) {
      toast({
        title: 'Insufficient Credits',
        description: 'You need 10 credits to generate a design.',
        variant: 'destructive',
      });
      return;
    }

    setIsGenerating(true);
    try {
      const generateDesign = httpsCallable(functions, 'generateCreatorDesign');
      const result = await generateDesign({
        prompt: editablePrompt.trim(),
        apparelType,
        surface: surface || 'front',
        category: 'Apparel',
        badgeShape: selectedOption.shape,
        badgeDimensions: selectedOption.dimensions,
      });

      const data = result.data as { designId: string; logoImageUrl: string; designImageUrl: string; creditsRemaining: number };

      // Create CreatorDesign object for UI
      const design: CreatorDesign = {
        id: data.designId,
        userId: currentUser?.uid || '',
        prompt: editablePrompt.trim(),
        category: 'Apparel',
        apparelType,
        surface: surface || 'front',
        logoImageUrl: data.logoImageUrl,
        designImageUrl: data.designImageUrl, // Will be null initially
        createdAt: new Date(),
        isPublished: false,
      };

      setGeneratedDesign(design);
      setIsPositioning(true); // NEW: Show positioning UI instead of preview

      toast({
        title: 'Logo Generated! ✨',
        description: 'Now position your logo on the apparel.',
      });
    } catch (error: any) {
      console.error('Error generating design:', error);
      
      // Check if it's a content policy violation
      const errorMessage = error.message || '';
      const isContentViolation = errorMessage.includes('Content Policy Violation') || errorMessage.includes('content policy');
      
      toast({
        title: isContentViolation ? '🚫 Content Policy Issue' : 'Generation Failed',
        description: isContentViolation 
          ? 'Your prompt contains content that violates our guidelines. Please revise your description and try again with family-friendly language. No credits were charged.' 
          : errorMessage || 'Please try again.',
        variant: 'destructive',
        duration: isContentViolation ? 8000 : 5000,
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleContinue = () => {
    if (generatedDesign) {
      onComplete(generatedDesign);
    }
  };

  const handleRegenerate = () => {
    setGeneratedDesign(null);
    setIsPositioning(false);
    setEditablePrompt('');
    setSubject('');
    setLogoPosition({ x: 0, y: 0 });
    setLogoScale(0.5);
  };

  // NEW: Finalize design with user's logo position
  const handleConfirmPosition = async () => {
    if (!generatedDesign) return;

    setIsFinalizing(true);
    try {
      const finalizeComposite = httpsCallable(functions, 'finalizeDesignComposite');
      
      // Convert logo position from drag coordinates to actual apparel coordinates
      const container = apparelContainerRef.current;
      if (!container) {
        throw new Error('Container not found');
      }

      // Apparel images are 1024x1024, calculate actual position
      const containerRect = container.getBoundingClientRect();
      const xPercent = logoPosition.x / containerRect.width;
      const yPercent = logoPosition.y / containerRect.height;
      
      const actualX = Math.round(1024 * xPercent);
      const actualY = Math.round(1024 * yPercent);

      const result = await finalizeComposite({
        designId: generatedDesign.id,
        logoPosition: {
          x: actualX,
          y: actualY,
          scale: logoScale,
        },
      });

      const data = result.data as { designImageUrl: string };

      // Update design with final mockup URL
      const updatedDesign = {
        ...generatedDesign,
        designImageUrl: data.designImageUrl,
      };

      setGeneratedDesign(updatedDesign);
      setIsPositioning(false);

      toast({
        title: 'Mockup Created! ✨',
        description: 'Your design is ready to showcase.',
      });
    } catch (error: any) {
      console.error('Error finalizing composite:', error);
      toast({
        title: 'Finalization Failed',
        description: error.message || 'Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsFinalizing(false);
    }
  };

  const handleDrag = (_e: any, data: any) => {
    setLogoPosition({ x: data.x, y: data.y });
  };

  const handleScaleUp = () => {
    setLogoScale(prev => Math.min(prev + 0.1, 1.5)); // Max 150%
  };

  const handleScaleDown = () => {
    setLogoScale(prev => Math.max(prev - 0.1, 0.2)); // Min 20%
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-6xl w-full max-h-[95vh] overflow-y-auto shadow-2xl">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b-2 border-[#5D4E37]/20 p-6 flex items-center justify-between z-10">
          <div className="flex items-center gap-3">
            <Sparkles className="h-8 w-8 text-[#006B3E]" />
            <div>
              <h2 className="text-3xl font-extrabold text-[#3D2E17]">
                Design Your {apparelType}
              </h2>
              <p className="text-[#5D4E37] font-semibold">
                {surface ? `${surface} side` : 'Front design'} • 10 credits
              </p>
            </div>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={onCancel}
            className="rounded-full hover:bg-[#5D4E37]/10"
          >
            <X className="h-6 w-6" />
          </Button>
        </div>

        {/* Content */}
        <div className="p-6">
          {!generatedDesign ? (
            <div className="grid md:grid-cols-2 gap-6">
              {/* Left: Apparel Preview */}
              <div className="space-y-4">
                <Card className="border-2 border-[#5D4E37]/30">
                  <CardContent className="p-6">
                    <p className="text-sm font-bold text-[#3D2E17] mb-3">
                      Your Canvas:
                    </p>
                    <div className="relative aspect-square bg-black rounded-lg overflow-hidden">
                      <Image
                        src={getApparelImage()}
                        alt={apparelType}
                        fill
                        className="object-cover"
                      />
                    </div>
                  </CardContent>
                </Card>

                <div className="bg-blue-50 border-2 border-blue-200 rounded-lg p-4">
                  <p className="text-sm text-blue-900 font-semibold">
                    💡 <strong>Design Guidelines:</strong>
                    <br />• Describe ONLY the design/logo (e.g., "a fierce lion head", "geometric mountain pattern")
                    <br />• Don't mention clothing (we'll place your design on the {apparelType})
                    {(apparelType === 'Cap' || apparelType === 'Beanie') && (
                      <><br />• <strong>Size:</strong> Circular badge design (20cm diameter)</>
                    )}
                    {(apparelType === 'T-Shirt' || apparelType === 'Long T-Shirt' || apparelType === 'Hoodie') && (
                      <><br />• <strong>Size:</strong> Rectangular design (20cm x 40cm vertical)</>
                    )}
                    <br />• Use vibrant colors for contrast on black
                    <br />• Bold, simple designs work best for printing
                  </p>
                </div>
              </div>

              {/* Right: Style Template & Subject Input */}
              <div className="space-y-4">
                {/* Style Template Selection */}
                <div>
                  <Label className="block text-sm font-bold text-[#3D2E17] mb-2">
                    1. Choose Your Style Template:
                  </Label>
                  <Select 
                    value={selectedTemplateId?.toString()} 
                    onValueChange={(val) => setSelectedTemplateId(parseInt(val))}
                  >
                    <SelectTrigger className="w-full border-2 border-[#5D4E37]/30 focus:border-[#006B3E]">
                      <SelectValue placeholder="Choose a style" />
                    </SelectTrigger>
                    <SelectContent className="max-h-[300px]">
                      {styleTemplates.map((template) => (
                        <SelectItem key={template.id} value={template.id.toString()}>
                          {template.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Subject Input */}
                <div>
                  <Label className="block text-sm font-bold text-[#3D2E17] mb-2">
                    2. What Do You Want on Your {apparelType}?
                  </Label>
                  <Input
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    placeholder="e.g., neon lion head, RV initials, anime skull with flames"
                    className="border-2 border-[#5D4E37]/30 focus:border-[#006B3E]"
                    maxLength={100}
                  />
                  <p className="text-xs text-[#5D4E37] mt-1">{subject.length} / 100 characters</p>
                </div>

                {/* Badge/Logo Size Selection */}
                <div>
                  <Label className="block text-sm font-bold text-[#3D2E17] mb-2">
                    3. Select Logo Size & Shape:
                  </Label>
                  <Select value={selectedDesignOption} onValueChange={setSelectedDesignOption}>
                    <SelectTrigger className="w-full border-2 border-[#5D4E37]/30 focus:border-[#006B3E]">
                      <SelectValue placeholder="Choose size and shape" />
                    </SelectTrigger>
                    <SelectContent>
                      {designOptions.map((option, index) => (
                        <SelectItem key={index} value={index.toString()}>
                          {option.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <p className="text-xs text-[#5D4E37] mt-1">
                    {selectedOption.shape === 'circular' ? '⭕' : '▭'} {selectedOption.dimensions}
                  </p>
                </div>

                {/* Final Prompt - Editable */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label className="text-xs font-semibold text-[#3D2E17] uppercase tracking-wide">
                      4. Final Prompt (Editable):
                    </Label>
                    <span className="text-xs font-bold text-[#006B3E]">
                      Credits: {userCredits}
                    </span>
                  </div>
                  <Textarea
                    value={editablePrompt}
                    onChange={(e) => setEditablePrompt(e.target.value)}
                    placeholder="Your final prompt will appear here. You can edit it before generating..."
                    rows={5}
                    className="resize-none border-2 border-[#5D4E37]/30 focus:border-[#006B3E] text-sm leading-relaxed"
                  />
                  <p className="text-xs text-[#5D4E37]">{editablePrompt.length} characters</p>
                </div>

                {/* Info Box */}
                <div className="bg-blue-50 border-2 border-blue-300 rounded-lg p-3">
                  <p className="text-xs text-blue-900 font-bold">
                    ✨ <strong>AI creates:</strong> Logo badge ({selectedOption.shape} {selectedOption.dimensions}) + Mockup on black {apparelType} {surface ? `(${surface})` : '(front)'} (10 credits)
                  </p>
                </div>

                <Button
                  onClick={handleGenerate}
                  disabled={isGenerating || !editablePrompt.trim() || userCredits < 10}
                  className="w-full h-14 text-lg font-extrabold bg-[#006B3E] hover:bg-[#005230]"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="mr-2 h-6 w-6 animate-spin" />
                      Generating Magic...
                    </>
                  ) : (
                    <>
                      <Sparkles className="mr-2 h-6 w-6" />
                      Generate Design (10 Credits)
                    </>
                  )}
                </Button>

                <div className="bg-amber-50 border-2 border-amber-200 rounded-lg p-4">
                  <p className="text-sm text-amber-900 font-semibold">
                    ⚡ <strong>How It Works:</strong>
                    <br />1. Describe your design idea
                    <br />2. AI creates logo + mockup (10 credits)
                    <br />3. Add a model photo (optional, 10 credits)
                    <br />4. Publish to Treehouse Store
                    <br />5. Earn 25% on every sale! 💰
                  </p>
                </div>
              </div>
            </div>
          ) : isPositioning ? (
            /* Logo Positioning Interface - Two Panel */
            <div className="space-y-4">
              <div className="bg-blue-50 border-2 border-blue-200 rounded-lg p-4">
                <p className="text-sm text-blue-900 font-semibold">
                  🎨 <strong>Position Your Logo:</strong> Drag, drop, and resize the logo on the right panel. The left shows your original transparent PNG.
                </p>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                {/* LEFT: Original Transparent Logo */}
                <div className="space-y-3">
                  <p className="text-sm font-bold text-[#3D2E17]">
                    Original Logo (Transparent PNG):
                  </p>
                  <div className="relative aspect-square bg-gradient-to-br from-gray-100 to-gray-200 rounded-lg p-8 flex items-center justify-center bg-[size:20px_20px] bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)]">
                    <div className="relative w-full h-full">
                      {generatedDesign?.logoImageUrl && (
                        <Image
                          src={generatedDesign.logoImageUrl}
                          alt="Original Logo"
                          fill
                          className="object-contain"
                        />
                      )}
                    </div>
                  </div>
                  <p className="text-xs text-[#5D4E37] text-center">
                    High-res transparent PNG for printing
                  </p>
                </div>

                {/* RIGHT: Apparel with Draggable Logo Overlay */}
                <div className="space-y-3">
                  <p className="text-sm font-bold text-[#3D2E17]">
                    Position on {apparelType} {surface ? `(${surface})` : ''}:
                  </p>
                  <div 
                    ref={containerRef}
                    className="relative aspect-square bg-black rounded-lg overflow-hidden border-4 border-[#006B3E]"
                  >
                    {/* Background: Apparel Image */}
                    <Image
                      src={getApparelImage()}
                      alt={apparelType}
                      fill
                      className="object-cover"
                    />
                    
                    {/* Overlay: Draggable/Resizable Logo */}
                    {generatedDesign?.logoImageUrl && (
                      <Draggable
                        bounds="parent"
                        position={logoPosition}
                        onDrag={handleDrag}
                      >
                        <div
                          style={{
                            position: 'absolute',
                            width: `${logoScale * 100}%`,
                            height: `${logoScale * 100}%`,
                            cursor: 'move',
                          }}
                        >
                          <Image
                            src={generatedDesign.logoImageUrl}
                            alt="Logo Overlay"
                            fill
                            className="object-contain pointer-events-none"
                          />
                        </div>
                      </Draggable>
                    )}
                  </div>
                  
                  {/* Scale Slider */}
                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <Label className="text-xs font-bold text-[#3D2E17]">Logo Size:</Label>
                      <span className="text-xs text-[#5D4E37]">{Math.round(logoScale * 100)}%</span>
                    </div>
                    <input
                      type="range"
                      min="10"
                      max="100"
                      value={logoScale * 100}
                      onChange={(e) => setLogoScale(parseInt(e.target.value) / 100)}
                      className="w-full"
                    />
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-4">
                <Button
                  onClick={handleResetPosition}
                  variant="outline"
                  className="flex-1 h-12 border-2 border-[#5D4E37]/30 font-bold"
                >
                  Reset Position
                </Button>
                <Button
                  onClick={handleConfirmPosition}
                  disabled={isFinalizingComposite}
                  className="flex-1 h-12 bg-[#006B3E] hover:bg-[#005230] font-extrabold"
                >
                  {isFinalizingComposite ? (
                    <>
                      <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                      Creating Mockup...
                    </>
                  ) : (
                    'Confirm Position & Continue'
                  )}
                </Button>
              </div>
            </div>
          ) : generatedDesign ? (
            /* Generated Design Preview */
            <div className="space-y-6">
              <div className="grid md:grid-cols-2 gap-6">
                {/* Apparel with Design */}
                <div className="space-y-3">
                  <p className="text-sm font-bold text-[#3D2E17]">
                    Your Design on {apparelType}:
                  </p>
                  <div className="relative aspect-square bg-black rounded-lg p-8 flex items-center justify-center">
                    <div className="relative w-3/4 h-3/4">
                      {generatedDesign.designImageUrl && (
                        <Image
                          src={generatedDesign.designImageUrl}
                          alt="Generated Design"
                          fill
                          className="object-contain"
                        />
                      )}
                    </div>
                  </div>
                </div>

                {/* Logo Only (for Printing) */}
                <div className="space-y-3">
                  <p className="text-sm font-bold text-[#3D2E17]">
                    Logo Only (Print-Ready):
                  </p>
                  <div className="relative aspect-square rounded-lg overflow-hidden border-4 border-[#006B3E]">
                    {generatedDesign.logoImageUrl && (
                      <Image
                        src={generatedDesign.logoImageUrl}
                        alt="Logo for Printing"
                        fill
                        className="object-cover"
                      />
                    )}
                  </div>
                </div>
              </div>

              <div className="bg-[#006B3E]/10 border-2 border-[#006B3E] rounded-lg p-4">
                <p className="text-sm font-bold text-[#3D2E17]">Your Prompt:</p>
                <p className="text-sm text-[#5D4E37] mt-1">{generatedDesign.prompt}</p>
                {generatedDesign.revisedPrompt && (
                  <>
                    <p className="text-sm font-bold text-[#3D2E17] mt-3">AI Enhanced:</p>
                    <p className="text-sm text-[#5D4E37] mt-1">
                      {generatedDesign.revisedPrompt}
                    </p>
                  </>
                )}
              </div>

              <div className="flex gap-4">
                <Button
                  onClick={handleRegenerate}
                  variant="outline"
                  className="flex-1 h-12 border-2 border-[#5D4E37]/30 font-bold"
                >
                  Generate New Design
                </Button>
                <Button
                  onClick={handleContinue}
                  className="flex-1 h-12 bg-[#006B3E] hover:bg-[#005230] font-extrabold"
                >
                  Continue to Model Showcase
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
